### PR TITLE
doc: add some small notes for grafana-operator

### PR DESCRIPTION
**Pull request by icy**
My editor has pushed quite a lot of space changes. Other than that, the patch provides some short help for `grafana-operator` user. I haven't found them in our doc, so I tried myself and got it here.

A thank  for the presentation at Berlin stackconf ;)

### CODE REVIEW

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Review by hagen1778 — APPROVED** [review]
LGTM!

**Comment by hagen1778** [comment]
Conflicts were resolved at https://github.com/VictoriaMetrics/grafana-datasource/pull/118

**Comment by hagen1778** [comment]
Closing this PR in favour of https://github.com/VictoriaMetrics/grafana-datasource/pull/118

Thanks again @icy !

**Pull request closed without merging**
