### PR TITLE
Add support queries prettifying in query editor

### PR DESCRIPTION
**Pull request by Loori-R**
- add a `prettify query` icon, which when clicked, formats the query. Related [issue #86](https://github.com/VictoriaMetrics/grafana-datasource/issues/86).
- change the style of the buttons `WITH templates` and `Run in vmui` to icons.

image

### CODE REVIEW

**Review by dmitryk-dk — DISMISSED** [review]
LGTM!

**Review by hagen1778 — DISMISSED** [review]
LGTM! 
But looks like linter isn't happy https://github.com/VictoriaMetrics/grafana-datasource/actions/runs/6176109877/job/16764451214?pr=101

**Comment by Loori-R** [comment]
@hagen1778 updated

**Review by hagen1778 — APPROVED** [review]
LGTM

**Pull request merged**
