### PR TITLE
Setup tests in CI

### PR DESCRIPTION
**Pull request by Loori-R**
- Run tests when opening a PR
- Run javascript CodeQL Analysis for PR

#45

### CODE REVIEW

**Review by hagen1778 — APPROVED** [review]
looks good to me.
@dmitryk-dk what do you think?

**Review by dmitryk-dk — COMMENTED** [review]
Overall looks good!

nit: we can add another two flags
```javascript
"test:coverage": "jest --collectCoverage",
"test:watch": "jest --watch"
```

I have run tests and got two of them failed
```javascript
src/querybuilder/components/MetricSelect.test.tsx (12.814 s)
  ● Console

    console.error
      Warning: An update to MetricSelect inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at query (/Users/dmitryk-dk/grafana-datasource/src/querybuilder/components/MetricSelect.tsx:38:32)

      90 |             setState({ isLoading: true });
      91 |             const metrics = await onGetMetrics();
    > 92 |             setState({ metrics, isLoading: undefined });
         |             ^
      93 |           }}
      94 |           isLoading={state.isLoading}
      95 |           options={state.metrics}

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:24064:9)
      at dispatchAction (node_modules/react-dom/cjs/react-dom.development.js:16135:9)
      at setState (src/querybuilder/components/MetricSelect.tsx:92:13)
```
```javascript
 MetricSelect › shows all metric options

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      58 |
      59 | describe('MetricSelect', () => {
    > 60 |   it('shows all metric options', async () => {
         |   ^
      61 |     render(<MetricSelect {...props} />);
      62 |     await openMetricSelect();
      63 |     await waitFor(() => expect(screen.getByText('random_metric')).toBeInTheDocument());

      at it (src/querybuilder/components/MetricSelect.test.tsx:60:3)
      at Object.describe (src/querybuilder/components/MetricSelect.test.tsx:59:1)
```

I think I should add the same for the backend part). Will do it

**Comment by Loori-R** [comment]
updated the test timeout. @dmitryk-dk, please check

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Pull request merged**
